### ISSUE TITLE
WiFi AP not updating 

### ISSUE THREAD

**Issue by LowTrunkOzz** [NimmLor/esp8266-fastled-desk-light#8]
Flashed both the sketch and spiffs files successfully but cannot update wifi to connect to a different ssid. The page that loads after entering ssid and password is only text that says Not Found

**Comment by visualdeath** [comment]
The WiFi connection you want to make has to be set in the secrets file. The WiFi page was left over from esp8266-fastled-webserver and the code to process it was removed by the original author so submitting the form does nothing.

**Comment by LowTrunkOzz** [comment]
Ah, that makes sense. I've since added WiFi manager so I don't have to hard code the connections, but that's good to know. Thanks.
